# -*- coding: utf-8 -*-
"""Overview of Colaboratory Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/basic_features_overview.ipynb
"""

#Calculadora em Python
print('*****************************Calculadora em Python*****************************\n')
print("Selecione o número da operação desejada: ")
print("1- SOMA")
print("2- SUBTRAÇÃO")
print("3- MULTIPLICAÇÃO")
print("4- DIVISÃO")
option = int (input("\nDigite sua opção (1/2/3/4): "))
num1 = int (input ("Digite o primeiro número: "))
num2 = int (input ("Digite o segundo número: "))
if option == 1 :
  result = str(num1+num2)
  print('%s + %r = ' %(num1,num2) + result)
  
elif option == 2 :
  result = str(num1-num2)
  print('%s + %r = ' %(num1,num2) + result)
  
elif option == 3 :
  result = str(num1*num2)
  print('%s + %r = ' %(num1,num2) + result)
  
elif option == 4 :
  result = str(num1/num2)
  print('%s + %r = ' %(num1,num2) + result)
  
else :
  print("Opção inválida!")